package com.atguigu.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.13
 * 2020-06-26T11:48:00.075+08:00
 * Generated source version: 3.2.13
 *
 */
@WebServiceClient(name = "RegionServiceImplService",
                  wsdlLocation = "http://localhost:7777/areas?wsdl",
                  targetNamespace = "http://serviceimpl.atguigu.com/")
public class RegionServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://serviceimpl.atguigu.com/", "RegionServiceImplService");
    public final static QName RegionServiceImplPort = new QName("http://serviceimpl.atguigu.com/", "RegionServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7777/areas?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegionServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:7777/areas?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegionServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegionServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegionServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RegionServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RegionServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RegionServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RegionServiceImpl
     */
    @WebEndpoint(name = "RegionServiceImplPort")
    public RegionServiceImpl getRegionServiceImplPort() {
        return super.getPort(RegionServiceImplPort, RegionServiceImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegionServiceImpl
     */
    @WebEndpoint(name = "RegionServiceImplPort")
    public RegionServiceImpl getRegionServiceImplPort(WebServiceFeature... features) {
        return super.getPort(RegionServiceImplPort, RegionServiceImpl.class, features);
    }

}
