package com.atguigu.serviceimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.13
 * 2020-06-26T11:48:00.054+08:00
 * Generated source version: 3.2.13
 *
 */
@WebService(targetNamespace = "http://serviceimpl.atguigu.com/", name = "RegionServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface RegionServiceImpl {

    @WebMethod
    @Action(input = "http://serviceimpl.atguigu.com/RegionServiceImpl/getRegionByParentIdRequest", output = "http://serviceimpl.atguigu.com/RegionServiceImpl/getRegionByParentIdResponse")
    @RequestWrapper(localName = "getRegionByParentId", targetNamespace = "http://serviceimpl.atguigu.com/", className = "com.atguigu.serviceimpl.GetRegionByParentId")
    @ResponseWrapper(localName = "getRegionByParentIdResponse", targetNamespace = "http://serviceimpl.atguigu.com/", className = "com.atguigu.serviceimpl.GetRegionByParentIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getRegionByParentId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
