
package com.atguigu.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://test.atguigu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param userName
     * @param userAge
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retValue", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://test.atguigu.com/", className = "com.atguigu.test.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://test.atguigu.com/", className = "com.atguigu.test.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userAge", targetNamespace = "")
        int userAge);

}
