package com.atguigu.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.13
 * 2020-06-27T21:54:23.066+08:00
 * Generated source version: 3.2.13
 *
 */
@WebService(targetNamespace = "http://test.atguigu.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://test.atguigu.com/", className = "com.atguigu.test.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://test.atguigu.com/", className = "com.atguigu.test.SayHelloResponse")
    @WebResult(name = "retValue", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userAge", targetNamespace = "")
        int userAge
    );
}
