package com.atguigu.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.13
 * 2020-06-26T14:07:10.366+08:00
 * Generated source version: 3.2.13
 *
 */
@WebService(targetNamespace = "http://impl.service.atguigu.com/", name = "UserServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface UserServiceImpl {

    @WebMethod
    @Action(input = "http://impl.service.atguigu.com/UserServiceImpl/addUserRequest", output = "http://impl.service.atguigu.com/UserServiceImpl/addUserResponse")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://impl.service.atguigu.com/", className = "com.atguigu.service.impl.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://impl.service.atguigu.com/", className = "com.atguigu.service.impl.AddUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.atguigu.service.impl.User arg0
    );
}
